#
# This is the Travis-CI configuration.
#

# This gets us a faster build via the container-based build system.
# It comes with some limitations but they shouldn't be a problem.
sudo: false

# The default is to get email notification of build results.  This is
# usually just spam.  Look at one of the many the web interfaces for
# build results.
notifications:
  email: false

# Configure more than one builder.
matrix:
  # Each included item will be a builder.
  include:
    # This builder will run our test suite directly.
    - env: ENV="testing"
      language: "python"

    # This builder will build the Nix packages (which happens to run the test
    # suite as well).
    #
    # tar on trusty doesn't have --exclude-vcs-ignores so disable it here.
    - env: ENV="packaging" EXCLUDE_VCS_IGNORES=""
      # Force this to run in a VM since the packaging script wants to launch Docker.
      sudo: "required"
      # We don't really need any particular language runtime.
      # Maybe the C runtime is lighter than the rest?
      language: "C"

# Install leastauthority.com's dependencies.
install:
  - "./test-tools/install-${ENV}"

# Run its test suite.
script:
  - "./test-tools/run-${ENV}"
