#
# This is the Travis-CI configuration.
#

# This gets us a faster build via the container-based build system.
# It comes with some limitations but they shouldn't be a problem.
sudo: false

# The default is to get email notification of build results.  This is
# usually just spam.  Look at one of the many the web interfaces for
# build results.
notifications:
  email: false

# Configure more than one builder.
matrix:
  # Each included item will be a builder.
  include:
    # This builder will run our test suite directly.
    - env: ENV="testing"
      language: "python"

    # This builder will build the Nix packages (which happens to run the test
    # suite as well).
    - env: ENV="packaging"
      language: "nix"

# Install leastauthority.com's dependencies.
install:
  - "./test-tools/install-${ENV}"

# Run its test suite.
script:
  - "./test-tools/run-${ENV}"
