apiVersion: 'extensions/v1beta1'
# Read about deployments at
# http://kubernetes.io/docs/user-guide/deployments/
kind: 'Deployment'
metadata:
  name: 'infrastructure-deployment'
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: 'infrastructure'
    spec:
      # Read about EBS volumes at
      # http://kubernetes.io/docs/user-guide/volumes/#awselasticblockstore
      volumes:
      - name: 'web-data'
        persistentVolumeClaim:
          claimName: 'infrastructure-web-pvc'
      - name: 'flapp-data'
        persistentVolumeClaim:
          claimName: 'infrastructure-flapp-pvc'

      # Read about containers at
      # http://kubernetes.io/docs/user-guide/production-pods/
      containers:
      - name: 'web'
        image: 'localhost:5000/leastauthority.com/web'
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: '/app/data'
          name: 'web-data'
        - mountPath: '/app/flapp-data'
          name: 'flapp-data'

      - name: 'flapp'
        image: 'localhost:5000/leastauthority.com/flapp'
        ports:
        - containerPort: 3116
        volumeMounts:
        - mountPath: '/app/data'
          name: 'flapp-data'
