apiVersion: ENC[AES256_GCM,data:17o=,iv:DqkDV/AR/NcKNDVPHKj4lyGxIrvcR5p3zYKlHPZtZRg=,tag:d/SllcsYkK7NegeTph3hKg==,type:str]
kind: ENC[AES256_GCM,data:TB6GDTvo,iv:9YNDFzI9vr6Pk40LETdRJ4u0W1GYkpSJ32f/8Ak00Kk=,tag:XH0OBzyoSrPF/iabBGkHpg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ibg=,iv:IfWaoBHvad9gBe6oZ7EueC+ERJueQ2QhvCiCsYKv1lg=,tag:W42rP79kw2xT4kT+Bz3HgQ==,type:str]
type: ENC[AES256_GCM,data:jrg+j1v4,iv:Rd62epasmv12+LcoR6D+RHN03rFLyyT8DqAyyZK5Cv0=,tag:/hlwQKy9KpWQtAON9A2tgg==,type:str]
data:
    domain: ENC[AES256_GCM,data:PMt9aErAkBCingSDRS3vaTHKDc6XFCMiFwaxyYLLLekc+tq2,iv:0uhmeFkM8OybK+mE/8tJ7dFgwP9Lra22PQ64j0wGUR4=,tag:CHUy5dCLRK1e5aiDXLm+uQ==,type:str]
    smtp.password: ENC[AES256_GCM,data:agoy8OTBOownrJBT4FqP1nSL7R846wsO2Ipo+mI1TwI5E7/ggY5QnA==,iv:ckdeUJTYryow6/YwixmNUoZ7tGS5HVnZT16LsQ82YLU=,tag:7/EeSX2mOTs6G2/I7Zfk8w==,type:str]
    stripe-private.key: ENC[AES256_GCM,data:qZnAJUoRxwLAia+ggPbTQzVsXMMyYEGy+p8HNUmvfGuLqveMarRq66HtvaY=,iv:mqFgCazLiYuUzk9DXJtJUQI0WUitpnp4Q5bS319rWD8=,tag:9MPeU2pl6FfF7m5+Itnp3w==,type:str]
    stripe-publishable.key: ENC[AES256_GCM,data:mE6TQb0M3QiEkBnBBwS0LaBiZvb2LYRD94q5O2ngr9ZMjYW5MvCJiEU4ihQ=,iv:M1BZxtPsdeUuAFFOrn/S+tdXXDEJLhJCuwyGJ59uiSI=,tag:nVB2LlaFAXokghV1qQzlrA==,type:str]
    aws-s4.id: ENC[AES256_GCM,data:FVKo8jfLSCMoGJhhjGCYbI80bVgBRy7tmHmQ6A==,iv:pESIMFvvVDSWg3UFUl4klfFDUfBiIjf1rpFuVRBmEuo=,tag:NM9vQcRmrHLHhJS7MmN5hg==,type:str]
    aws-s4.key: ENC[AES256_GCM,data:3J8Pv2/gwyL2wLjuwwFL/ewMfOn2Jy5ecEptFRkDw8VlzTTXnzW0lJ7TAX1vekwqouWYCxOvA/U=,iv:6sl/bW/b9CAO6d+yHBN+EF/ywhBAXtGe0zvxz/3jGrs=,tag:lrgnq3IgslUvCdCyd8Utug==,type:str]
    fluent-s3.conf: |-
        ENC[AES256_GCM,data:GZ3Vh0DpFZs3VZkMAUhcVpOy4Hgf+ReLFw8BkfTiBMUQN+ET+yH59lfFqhjn+C6JGC491kqEDtJKIkQygdOLojOW4p02vmdOHWHbf80NlTlLRwVWrpNiN2aAvbEu/7XePbJ9zamCMbVTnOo9HM5v7fs0ND45OycBzzIl7w/F6o3hsXkHAGyZADI4Zt/GHI0eoJ3KPmCy/OUuvyvVN1xURARPnVqFIzZoxzvCscz5doQaBhMANl819vtkll0dA20PN5PpdDKQpjargim/zdAdyhzSxGs/,iv:1UT/oloxIwyxS7cZObPpw9V3uWif5IB/G+lCRLnvKBQ=,tag:DRbqu+49Viz7AAu1nGYh7g==,type:str]

    website-cert.pem: |-
        ENC[AES256_GCM,data:6kobAjN8exjwM4Bt1mUGtjGjJoOCOb87Voscm1RIc8/UpZQXX0xxMsPIgQfj7XolV+OHus2UBIbEGy3hKUA4JnaXmdLXcqvLbiAmVluyM2dcOy5HGla0xTgF04aNJlBWgCS9t0oFr1TkMV/A4oUlop8PseRui4xsyNKnQIAAQbliBkNJW5/0aPe8NIqF8+i7/6AH98EoYuH98x0MddQS1fChlp6NCruRjgP+lQWHzsjBj5cN97ddEbQ/HY6gagnu+FLrO69zcVgNmVfrtw1pqkd5q2qD5bSR3Snw0gGYQ7qA8SuraAf2ZsIHA1jn1LJFr5sImfXu99Ikn0AvA+rvUvNkBThbv4Et8K2GAkBaNoTDLhJuTMqrZsWxMQ0sYYIB8OuBa4SKdTvZ+ptBMOE8zULPivMpdKnN/RwyFRWH3UUB3bGDTPxFsbYbHV9E8ywCRlBhLjHUjSsOmgDPmnwkZz10ds7YD5eo8gYgRHwPy/7taX/MwcT/s1ernf8gS5OgXayJWt9VFs4kvCKEtUc2F7xcYabXyxVZ2eL/Yg5rsbNhuIHWjr7VxjChLy8SlIIIUp73FHMoGVjPubyjdBq7ts+LhlVeCuEQt4tdHQZ1nh7i+ChlnBD7lHxjvYYBtl4zu5kAZOptPqZA6jIqmo/ACYKzB1LXteMYv8qUgdjlO3br0W27J5X2wivdIXhN62krTWoWmt6Kjm3198RHCk2vV5pxzSWXpgotnM8eRaI6H912jHuPgiMX9Igj/xOtjEBnZcHX2P1gzsbCvMhPIWrHl0AD4uMRHTwGNDp422nWM9FJzg9PmB0/SR+g9VTgJ3EnO7Z43oAeeLQYdChg1Dc0hbg05+SZhQSMATNAKqhUh/f+9OTmgiKL1mt92LF/PXUSYdhNOYxemMUIe83S8L/znA5S36i6h3H4lfVf7BYpUjMANzcvOPwP8mdliSoOiA==,iv:d0fxEMyPW3EgZeYaNpXB2uh1o5wmegRVJMAy+cWwOBc=,tag:CYWPc0wjjVU6GTJUz/lFrg==,type:str]

    website-chain.pem: |-
        ENC[AES256_GCM,data:dn3T2AMmt/A67u5loPOpNj1AIcXsvXrHCBy1wO0oWSGbfnWOS4xceWpIu5aD8GuWNcao171vRtXqPc9Hxf9au7HUH5uPYKlYlM7V6Qk5yp0UmXe8A0LNjBWDTVd2+ssFDWQJyAjZ0myrJV5efYOr8luoNtO5RiCgpPta27nMoxa0TN/fkHzMISpVffE6Nj66nV8h8KKIgp6/CbpaIPvXAN6kF98+Lrnr+M59qdPFxtGom5gTNFLNbsVKzTIkAmht2h9Grv5PHAn5EpqJplHVjkGeKS+qSWCSy/zXvDGrpXmw15Bd4TEbtTKC1rvdxwwCfjFntXjxwgXrMMIsQnpH/nqR2Zakb2Ata5diznyaq6BQRPAKTy6EroMpYNe2eayJpb5JL0Ymltjo8Qd0GIHghCeBcD9DKumQOeafMJbfNu9J2rg+D38Ioqa6EWwEgfPsRpDovpytaQ5n5MxiuD9L655P+V+ONaQNZ6nH/38c5m4AybX1j+mIFFKLrut7PZ35909e7hTGx3XfdTO0PcVK71R3HvsfCYfml1YphCDRdYgz29jU7yJqGzE0YqjpW1EAcghAGbF6Fe405PRpnzFnAvftd5AgD2WYsi2dtVye62okWZfrj/57NxFu99HKWA9C5jlDnVs3IhQJ0Z1dspGDbDrOd5+gqVA3GJ4oKPI2IR7QvqEeFSnOsY4V2cnWsNjYIOu00DY3/16H1fas1V/Eb9Xo2dvOSNK6nG5dzz9/n95+mDk5WXFrNBp1uxcVkrZ4hIZttJdm/wRHS5o+Z2SlUEXKmoLv91VQTQyJvYU9GrQ/FNGowQbvbK2VgXFcqRu03tZl1dVgOXoH0HUJUutP73uPwhOAmpP9U8I5i8A2Q3I92JpxUCYjAL1Wyr7qD7crhajhdguspjnsNKN1lZwUc5T9rto8aghWQWKf+iN9evMbtYsTaFfY42Tu,iv:3PmhaiheztqIvdpqJ3D/yTZMPaeNChv2fwXq0FzB1bo=,tag:SeAy/7ZHWXtkqEmljSBb0A==,type:str]

    website-key.pem: |-
        ENC[AES256_GCM,data:KIYIl81CbK5bEn2GwJGuFdeqrQ5dVQfyMOy7kyk3VTEVie25RngLwIFXUDpECN0Q5c8HEzN3qBCPypV987xXJhRUStnwXPaZy6Sn6SL7fXBIHzb0JEre67NBYJ5HVMtyUnfFqt+X22RbvVNDi4o3lGCuZJsBMpcSYbmQPX02bE5cuxcBl/nk+Jafdng45X4/Ep1DIJiyZXN80tXZM2IKrptUMz35iBSr8MKRU7rnma5QSEZ3CAP7Qn8YIKQt2dANhOVLLHoA5Rp3plJMbz6+qWaeQDvyrHW2PxABOOzMxmCTvNAvLmHukZP9e5jVaMkWcjgP8Prm3eY8stkSl5uQwoRvFbPR9/HKGr/DGqmyC5PuUjCQauyExx2Z2KllXcc0IFBqoX+XNo4kovbYNLyFLPplzZ4H053uF8NyBDMD6RnBUHUIR5JaBawgykRi23MrIhGy0pxIhhyvH/vfKiUp0n7OvIQo8hggcjb70tqY4eLZOT+HSgFVJkZ7aChTpbC9LGJnO7UzcaSVD4NxZLFE80JesVy1P+QAPcKxaL4wmUEE+kT2adOf/3xsY90Wn2LBjexaXLakMcSTo9HXFUcQT27zjOGS4SIfhZ+OA59wZ1o5ZTKUuD2NwOVFt7h2b9w6zTHG7xIfn/dwov+E+t7ULFO87j5uqxfBDSOtFROE0oPY6lnN5/dVt9mY9H3aKhKaztM6UuNq8OAj7GIsEGwnMcZgy6Mud1PB+EdL35wj/PKVP2D4FZRjyHaZiqkGIu+16IE0Y24UEVoIzssVKxPLYKaJglnq5F0VxAtULheGP49a7HcUGWYnhn4odxYeYVCeoFPkB+9Ur4/fIi6sZTcKqL9Rp60I7qk3qq4wN9TS7p8Y6CvcpbmnHIzQj26tC/T7Vg==,iv:LFsg2DEW/6lLEe2oiaULHjoSXDhAUm+bTVWn9tsjUHc=,tag:zXSWvddQMeBXt/dLWhcMTw==,type:str]
sops:
    mac: ENC[AES256_GCM,data:QOuq15TaT+9/1xLTA+YaKhzR9ledtVyd9OudmKSHsQ395RSKJi1j2iAsRg7kFQC2sMrGmFEcQbSxeIobfGzdQzbA5vVG4G18Ed+tRhyD2ERpk0mYeRiJmYz82ubhsvqO2WiG0bavEMSTg5JMNXavIY2hw0nlBEkfavj9mwCgM9Q=,iv:v0uHjDBI8budTX/p8TLh04U8KQWTxY8TlxSscmFSP+Q=,tag:6A4Iepd6kRoixOGC0789ZA==,type:str]
    version: '1.16'
    pgp:
    -   fp: 96B9C5DAB2EA9EB679419DB7E27B085EDEAA4B1B
        created_at: '2017-06-09T17:37:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAzNqg1saGXvSAQgAgViRyuosVWHaT0v0fqgJL0fdTWNbLOclvctRk4TFqo3c
            VMBMSggO2Ubvs2+gHTCHLhGPfVcalk0bUD/jT/Fvyy9c+VZ8bDMAxB+mIg0PU74f
            6/r4Sf2vNEsjcGZYfm6jWXRGdcV1VvvYOchIK8gcMMPy/DhNL4r/eVuP2h2IS7Jy
            NzYXK5Yg08/U+3h8YPY9OKpyXkDNtyUZ/bnc6vmLIg90tg0eidCroCvfBKRQVoaM
            cR14hP0S6hG5XRrCRFGkg6sifSLeI1lTKFlVurgUPuEDzU14u8A7+V19gnpNIFZM
            1+j/Is2Ay0Z0j0FaBFmZNiBufM5CJ/3RBfgM32uGN9JcAW95ocFiYdLmJ6oWjoN6
            k14fIN+yRWIoAh8yFuk8BZeJLEPrXUGaSz7EtgACgYJ0xXOeT83wtzU695q4R5Vg
            lnt5WNMlkRi0v/9rZkZLQYRBWymAVxjDeL4L3K8=
            =wVyT
            -----END PGP MESSAGE-----
    -   fp: 9D5A2BD5688ECB889DEBCD3FC2602803128069A7
        created_at: '2017-06-09T17:37:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA5lOukqRk5SQAQf/fg7SBhRL8MJML+VSSSF4w/WRErhDKYTYKjzOzGoyrm8q
            iunnQpJ7bAYBPpu5XnJHbpKwZncJKYIPXeoDeb9/8KB0yhzHnnKQ/ARRrN2gpIYr
            /E+4r729M9k7Fx8IY0bfVQpcOvJPwazRfTV92nWK++AOZWTRwQJ9pX6LImt+JI2R
            g8PpctY7Lw3+9xeCbThjYXCQCEgnKYORU3o0yUWs9SGA8T+DFR4hYN4TTHWYsHBU
            WkXFjowip7cm5V8rkKw1awVJhcHecj74AEvrLRsYeMMATyf9dSnFiBvK1Id6t43q
            jmetw1vaQBlH2XMPXxsl5jpPbHekw9tx6aGxtn7B4tJcAYkqI7r86APxLY06eIcI
            UUsHPDBS8QmRaL0IV3PxHT+1MWNE4psVXxpNtRt7JmRooRAoNepFEHkXZLBYjw4D
            aArprdGEF6744GT8GLSS1zJijNk4KCDLhb0bz/Y=
            =RBzN
            -----END PGP MESSAGE-----
    lastmodified: '2017-06-12T17:58:04Z'
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    unencrypted_suffix: _unencrypted
