# Read about PersistentVolumes at
# http://kubernetes.io/docs/user-guide/persistent-volumes/
kind: 'PersistentVolume'
apiVersion: 'v1'
metadata:
  name: 'infrastructure-web-pv'
spec:
  capacity:
    storage: '1G'
  accessModes:
    # One node can mount this read-write.
    - 'ReadWriteOnce'
  awsElasticBlockStore:
    # Manually created via
    #   aws ec2 create-volume --availability-zone us-east-1a --size 8
    volumeID: 'vol-01d518bc53892d142'
    fsType: 'ext4'
