# Read about DaemonSets at
# http://kubernetes.io/docs/admin/daemons/
#
# Also note this is something of a hack.  It proxies Docker registry
# requests from localhost to the the kube-registry-service.  This
# works around Docker's complaints that the access is insecure because
# we haven't set up TLS for the registry.  If we set up TLS for the
# registry Service, Docker on each node could just talk to it
# directly.
#
apiVersion: 'extensions/v1beta1'
kind: 'DaemonSet'
metadata:
  name: 'kube-registry-daemonset'
  namespace: 'kube-system'
spec:
  template:
    metadata:
      name: 'kube-registry-proxy'
      namespace: 'kube-system'
      labels:
        name: 'kube-registry-proxy'
    spec:
      containers:
      - name: 'kube-registry-proxy'
        image: 'gcr.io/google_containers/kube-registry-proxy:0.3'
        resources:
          limits:
            cpu: '100m'
            memory: '50Mi'
        env:
        - name: 'REGISTRY_HOST'
          value: 'kube-registry.kube-system.svc.cluster.local'
        - name: 'REGISTRY_PORT'
          value: "5000"
        - name: 'FORWARD_PORT'
          value: "5000"
        ports:
        - name: 'registry'
          containerPort: 5000
          hostPort: 5000
